### ISSUE TITLE
I get "Dilbert.com is not avaible", but it is

### ISSUE THREAD

**Issue by quite** [smarek/Simple-Dilbert#20]
Maybe some change has been made to the site.

**Comment by smarek** [comment]
Hello, yes, changes have been made today on dilbert.com, I'll update the application in 24h hopefully.

**Comment by smarek** [comment]
Fixed in version 4.1 (build code 34), see commits from 14th Jan 2015 in tag v4.1 ( https://github.com/smarek/Simple-Dilbert/tree/v4.1 )
