### ISSUE TITLE
Feature Request: Default zoom

### ISSUE THREAD

**Issue by mdn-united** [smarek/Simple-Dilbert#21]
Hi developer,
could you please add a default zoom value?
I always zoom the strip twice to have one part of the picture as big as possible. 

Thank you!

**Comment by smarek** [comment]
That's actually neat idea, I'll push it in next version. Thanks for suggestion

**Comment by mdn-united** [comment]
Hi smarek,
when will the next version be ready? 
It's been a while since my suggestion.

Cheers,
MDN

**Comment by smarek** [comment]
Provided with 4.2 which was today finished and will be available (if you do use F-Droid repository) in matter of days
