### ISSUE TITLE
Feature request: offline mode

### ISSUE THREAD

**Issue by nutpantz** [smarek/Simple-Dilbert#24]
It would be nice to have an option to download 20 -50 random comic strips
To look at offline. Maybe an option to automatically save every comic strip viewed
As default with a remove option for undesirable ones.. Like a reverse favorites.
Just found your app. Like it a lot so far, glad to see it on fdroid.

**Comment by smarek** [comment]
Hi @nutpantz 
already downloaded strips are available offline, regarding offline mode, that's possible for sure. Thanks for support :-)

**Comment by smarek** [comment]
Provided 4de105680afe63bd087e602b2477e0f05309a080
