### ISSUE TITLE
"Dies Teilen" ("Share this") doesn't work with 4.3

### ISSUE THREAD

**Issue by retsifp** [smarek/Simple-Dilbert#35]
Since the Update to 4.3, sharing within the App doesn't work anymore. When I select it, nothing happens. Before (with 4.2) it worked flawlessly.

**Comment by Kasijjuf** [comment]
I just tested this and can confirm: sharing is broken in version 4.3. I am using the app in English.

**Comment by smarek** [comment]
Fixed, will be released, 4fee48b87f6739339321207b8d15fe0cddb3c7e6
