### ISSUE TITLE
version 4.3: widget still not working with android 6.0

### ISSUE THREAD

**Issue by mvrk80** [smarek/Simple-Dilbert#36]
The widget doesn't show the strips.
If I open the strip in the app, then reload the same strip in the widget, the widget finally show the strip properly.

**Comment by smarek** [comment]
I don't have Android 6.0 for testing sincerely no more, Android 5 and Android 7 in my env worked always, with 6 it appeared to me, that sometimes you have to refresh/download the strip twice on widget, because of different handling of JPG/PNG format (JPG is for standard, weekday, strip, PNG is for sunday strips usually)

**Comment by smarek** [comment]
I've just tested with Android 6 (some Samsung device), what I've observed, is that widget works, even when given strip was not loaded in the app itself (only-widget case), but I had to click a refresh few times.
Does this work the same way in your device @mvrk80  ? Thanks

**Comment by mvrk80** [comment]
sorry for late answer.
Yes, you'right. I have to refresh on widget 12-16 times and the strip becomes visible.

**Comment by smarek** [comment]
Cool, does the number of refresh actions differ, if you take longer time between them? Ie. I suspect caching component to be responsible for different format of image, when it comes from in-memory and from disk cache (decode is needed).

Could you for example try refreshing once, using the phone for a tens of seconds/one minute, and then refresh again? 

I think if you keep refreshing back-to-back, the number is higher ... Thank you

**Comment by mvrk80** [comment]
Right again.
If I select a day, then wait 30 seconds, then refresh once, the strip appear!
:-)
