### ISSUE TITLE
Donation with Bitcoin

### ISSUE THREAD

**Issue by VernonSmith** [smarek/Simple-Dilbert#42]
Hi @smarek,
thank you so much for your awesome [Android](https://www.android.com/) app! 😍
What do you think of adding your [Bitcoin](https://bitcoin.org/) address to the _Donation_ section below your [PayPal](https://www.paypal.com/)?  😉

**Comment by smarek** [comment]
Hi @VernonSmith, there previously was this option, but I lost access to wallet.
If you want to, current address is [`131525CJ6UAzeqFiwG4Jsoq3GZrq5armJD`](https://blockchain.info/address/131525CJ6UAzeqFiwG4Jsoq3GZrq5armJD)

I'll add this to README, and close this ticket after, thank you!
