### ISSUE TITLE
Display strip title

### ISSUE THREAD

**Issue by JonnyTech** [smarek/Simple-Dilbert#44]
Every strip has a title, is it possible to display the title with each strip?

**Comment by smarek** [comment]
@JonnyTech thanks, title is not on many strips, but I've added support for displaying it, if it's available. Please watch for version 4.5 in F-Droid updates.

**Comment by smarek** [comment]
Oh, and one more thing. You need to refresh every single strip, which you have already cached, or the title will not display.

Use either:
  - single tap on image 
  - use menu > refresh option
  - for widget use reload button

**Comment by JonnyTech** [comment]
Excellent - thank you very much!
