### ISSUE TITLE
The zoom button do not respond 

### ISSUE THREAD

**Issue by beckysophie** [smarek/Simple-Dilbert#45]
***Expected Behavior***

The zoom feature provided in the App is to allow users view and to zoom any picture of their choice smoothly, so as to understand them better!!! 

***Actual Behavior***

The zoom feature do not work as the zoom button just clicks, without altering any change.... 

***How to produce the bug***

Open the app, after some of the pictures must have load, click on more options at the top right corner and then press the zoom button.... 
It won't zoom, it would just be the same 

* Operating system : Android 6.0
* Phone : Infinix hot s
* Simple Dilbert v4.5

***Recording of the bug is showned below......***

Watch the video below to see how it behaves.... 

https://youtu.be/qWQI1LQ6vqs

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/the-zoom-button-do-not-respond">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by JonnyTech** [comment]
As I understand it, the zoom button will reset the zoom to fit the whole strip on the screen. To zoom in or out you need to pinch the screen with two fingers.

**Comment by smarek** [comment]
@beckysophie thank you for report. the button actually does not change the zoom level, it applies the default zoom level, set in application preferences. To actually zoom in/out you have to use either "double-tap" or "pinch-to-zoom" gestures.

This behavior was changed in https://github.com/smarek/Simple-Dilbert/commit/88f50788a4e1d28db5e357b9e1e204c15fa8a7f5 on 8th June 2016, so it's really long time.

So I don't really think this is bug, maybe the menu item label is misleading.

How about we change the current one to "Default Zoom", and add another one, which will cycle through zoom levels (minimum / medium / maximum) when triggered? However this is still somehow ugly

**Comment by beckysophie** [comment]
What I mean is that the button doesn't alter any effect....

**Comment by smarek** [comment]
If you set default zoom in settings, return to strip view, change zoom
(double-tap or pinch-to-zoom) and hit the zoom button. Does it return to
default zoom level from settings?

**Comment by beckysophie** [comment]
@smarek do you mind if I make a copywrite for this wonderful app  ?
