### ISSUE TITLE
Duplicate toolbar icons and menu entries sometimes

### ISSUE THREAD

**Issue by acidstout** [smarek/Simple-Dilbert#46]
To reproduce:
1. Open app in portrait mode
1. Rotate device to landscape mode before the comic finished loading
1. Duplicate favorite buttons in toolbar appear as well as duplicate menu entries

![](https://i.imgur.com/GGt3R1n.jpg)
![](https://i.imgur.com/TNpIsuw.png)

**Comment by smarek** [comment]
This should be fixed with new SDK, please check in new release 4.6 coming out today, Thank you!
