### ISSUE TITLE
Sharing to whatsapp fails, when `don't share image just URL` is unmarked 

### ISSUE THREAD

**Issue by onos1** [smarek/Simple-Dilbert#49]
#### Expected behavior
After unmarking the `don't share image just URL` option in the app, I wanted to share both the image and URL to whatsapp contact, so I expected to use the share option and send the image to my contact.

#### Actual behavior
I was unable to share the image using the share option to whatsapp, because it brings back to the app after selecting share to whatsapp and give me a failed feedback response. 

#### How to reproduce
* Download the simple dibert  app [here](https://f-droid.org/repository/browse/?fdid=com.mareksebera.simpledilbert
* go to settings after clicking the three dot at the right top corner 
* unmark the `don't share image just URL` option 
* go back and click on `share` option 
* select whatsapp as means 
Failed!

* Mobile: Infinix note 4
* Operating system: android 7.0
* version 4.5

#### Recording Of The Bug
https://youtu.be/AqUIJiHngm0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/sharing-to-whatsapp-fails-when-don-t-share-image-just-url-is-unmarked">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by smarek** [comment]
This should be fixed with recent PR #54
