### ISSUE TITLE
Image still sending after ticking `don't send image just URL`

### ISSUE THREAD

**Issue by onos1** [smarek/Simple-Dilbert#50]
#### Expected behavior
Wanted to share image URL with friends, after ticking `don't share image just URL` I expected when image is sent only the URL will be sent

#### Actual behavior
The image actually sends and no URL was included, only an image title was shared including the image which is not meant to be shared but just the URL 

#### How to reproduce
- Download the simple dilbert app [Here](https://f-droid.org/repository/browse/?fdid=com.mareksebera.simpledilbert)
- click three dots on top right corner 
- select settings
- make sure `don't share image just URL` is clicked 
- try sharing an image 
Image still send

* mobile device: Infinix note 4
* Operating system: android 7.0
* version: 4.5

#### Recording Of The Bug
A video to display the bug 
https://youtu.be/uEE8N9329kU

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/image-still-sending-after-ticking-don-t-send-image-just-url">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by smarek** [comment]
Fixed by 953f7fe3d2c4527733f504092779ef62fedb541e
