### ISSUE TITLE
Wrong comic displayed

### ISSUE THREAD

**Issue by jakobcornell** [smarek/Simple-Dilbert#51]
For some dates the wrong comic loads consistently. The displayed comic appears to be a duplicate of a recent past comic. For example, The comic displayed for May 7, 2005 is the one from May 2, 2005. (May 3-5 also display this comic). The image loaded by "Open in Browser" is the same incorrect comic. I suspect this occurs elsewhere as well, because I've had comics appear repeatedly several times.

App version: 4.5

**Comment by jakobcornell** [comment]
It looks like this problem is associated with comic series. For example, in the ["New guy with a stress hump" series](http://dilbert.com/series/51), every comic in the series shows up as the first (May 9, 2005).

**Comment by 3DES** [comment]
I found the bug and will try to provide a fix as soon as I find some time within the next days....
