### ISSUE TITLE
Doesn't work with default browser 

### ISSUE THREAD

**Issue by jhoc2000** [smarek/Simple-Dilbert#58]
I use Internet (https://play.google.com/store/apps/details?id=com.lechneralexander.privatebrowser) as my default browser for security reasons but when I open the Dibert app it says Dilbert.com not available. There needs to be an option to choose which browser to use or please make it work in privacy browsers.

**Comment by smarek** [comment]
Hello, the app does not use any browser at all. What version of app do you have installed? This problem was maybe in version 4.4 through 4.6, however shall be fixed in 4.7

**Comment by smarek** [comment]
Might be, I haven't had chance to test Pie on real device, only AVD. Are you skilled enough, to take a look into LogCat (ie. adb logcat) ?

**Comment by jhoc2000** [comment]
I just noticed that if I don't go through a VPN it loads. Can Orbot's VPN be added to the code?

**Comment by smarek** [comment]
Oh, nice find, I don't think it's issue with specific VPN, Orbot uses standard Android VPN interface to route traffic through. What might be issue, if the network is slow enough (using Tor), the app might actually consider the request failed, because it takes very long to load.

Still to pin-point actual issue, could you take a look into LogCat for messages connected to the Simple Dilbert?

**Comment by jhoc2000** [comment]
Now it's stopped working again.

I've never looked at LogCat. My phone isn't rooted but I can load ADB onto my Linux computer. If I do will I be able to then see LogCat? Can you tell me where LogCat is located or aren't you talking about a file?

**Comment by smarek** [comment]
Yes, with linux it's easiest, there is usually package containing ADB (utility to talk to your phone over USB or IP), look for packages such as `adb`, `android-tools-adb` or similar

After you install it, this command should work `adb logcat`
Showing console of logs that your phone produces (similar to syslog), you might or might not grep it (ie. `adb logcat | grep -i dilbert`), but you're for sure looking for keywords ERROR(S), WARNING(S) and EXCEPTION(S), Java exception/error stacktrace is multi-line debug log

If you want, you can send me full logcat (catch ie. using `adb logcat 2>&1 > logcat.log`) and I'll look through it for relevant info

**Comment by jhoc2000** [comment]
Sorry for my late reply.

Please find attached a text file containing the output from the
command:

adb logcat | grep -i dilbert

Although I'm not familiar with Android output, it seems that
SimpleDilbert isn't on some sort of whitelist. Hopefully you can make
more sense of the it.

I look forward to your reply.


On Fri, 2019-01-11 at 23:57 -0800, Marek Sebera wrote:
> Yes, with linux it's easiest, there is usually package containing ADB
> (utility to talk to your phone over USB or IP), look for packages
> such as `adb`, `android-tools-adb` or similar
> 
> After you install it, this command should work `adb logcat`
> Showing console of logs that your phone produces (similar to syslog),
> you might or might not grep it (ie. `adb logcat | grep -i dilbert`),
> but you're for sure looking for keywords ERROR(S), WARNING(S) and
> EXCEPTION(S), Java exception/error stacktrace is multi-line debug log
> 
> If you want, you can send me full logcat (catch ie. using `adb logcat
> 2>&1 > logcat.log`) and I'll look through it for relevant info
> 

01-15 12:02:24.919 23866 23882 I AD-PLUGIN-RedPacketRainManager: Current packageName is com.mareksebera.simpledilbert
01-15 12:02:24.921 23866 10570 I AD-PLUGIN-SplashController: offline package com.mareksebera.simpledilbert false
01-15 12:02:24.923 23866 10570 I AD-PLUGIN-SplashConfigCache: packageName:com.mareksebera.simpledilbert, showInterval:600000
01-15 12:02:24.923 23866 10570 I AD-PLUGIN-SplashController: isAppSplash intent:Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mareksebera.simpledilbert/.core.DilbertFragmentActivity bnds=[540,879][731,1151] (has extras) } aInfo:ActivityInfo{538d0c0 com.mareksebera.simpledilbert.core.DilbertFragmentActivity} showType
01-15 12:02:24.923 23866 10570 I AD-PLUGIN-SplashController: requestSplashScreen duration:7, package:com.mareksebera.simpledilbert
01-15 12:02:24.924  1622  2680 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mareksebera.simpledilbert/.core.DilbertFragmentActivity bnds=[540,879][731,1151] (has extras)} from uid 10217
01-15 12:02:24.928   682   682 E ANDR-IOP: IOP HAL: Received pkg_name = com.mareksebera.simpledilbert pid = -1
01-15 12:02:24.935  1622  2680 D ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{a3dfcc2 com.mareksebera.simpledilbert}
01-15 12:02:24.935  1622  2680 E ActivityTrigger: activityStartTrigger: not whiteListedcom.mareksebera.simpledilbert/com.mareksebera.simpledilbert.core.DilbertFragmentActivity/40
01-15 12:02:24.936  1622  2680 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{a3dfcc2 com.mareksebera.simpledilbert} is now in focus and seems to be in full-screen mode
01-15 12:02:24.936  1622  2680 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.mareksebera.simpledilbert/com.mareksebera.simpledilbert.core.DilbertFragmentActivity/40
01-15 12:02:24.945  1622  2680 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{a3dfcc2 com.mareksebera.simpledilbert} is now in focus and seems to be in full-screen mode
01-15 12:02:24.945  1622  2680 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.mareksebera.simpledilbert/com.mareksebera.simpledilbert.core.DilbertFragmentActivity/40
01-15 12:02:24.957  1622  1695 D Boost   : hostingType=activity, hostingName=com.mareksebera.simpledilbert/.core.DilbertFragmentActivity, callerPackage=is.shortcut, isSystem=false, isBoostNeeded=false.
01-15 12:02:24.958  1622  1695 I ActivityManager: Start proc 10605:com.mareksebera.simpledilbert/u0a169 for activity com.mareksebera.simpledilbert/.core.DilbertFragmentActivity caller=is.shortcut
01-15 12:02:24.972 10706 10756 D PowerKeeper.Event: notifyAMProcStart processName: 10169 reason: com.mareksebera.simpledilbert, pid:0
01-15 12:02:24.978  3762  3780 D GameBoosterService: onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.mareksebera.simpledilbert', mForegroundUid=10169, mForegroundPid=10605, mLastForegroundPackageName='is.shortcut', mLastForegroundUid=10217, mLastForegroundPid=23381, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=1}
01-15 12:02:25.142  1622  1701 I ActivityManager: Displayed com.mareksebera.simpledilbert/.core.DilbertFragmentActivity: +192ms
01-15 12:02:25.159 10706 10756 D PowerKeeper.Event: notifyActivityLaunchTime: com.mareksebera.simpledilbert/.core.DilbertFragmentActivity totalTime: 192
01-15 12:02:25.302   712   805 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.mareksebera.simpledilbert#0
01-15 12:02:25.302   712   805 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.mareksebera.simpledilbert#0
01-15 12:02:25.351  1622  1701 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{9f1d591 u0 com.mareksebera.simpledilbert/.core.DilbertFragmentActivity t1427} time:667310394
01-15 12:02:25.673 10605 10629 W System.err: 	at com.mareksebera.simpledilbert.utilities.d.a(Unknown Source:89)
01-15 12:02:25.673 10605 10629 W System.err: 	at com.mareksebera.simpledilbert.utilities.d.doInBackground(Unknown Source:2)
01-15 12:02:25.691 10605 10605 I Toast   : Show toast from OpPackageName:com.mareksebera.simpledilbert, PackageName:com.mareksebera.simpledilbert
01-15 12:02:26.426 10605 10638 W System.err: 	at com.mareksebera.simpledilbert.utilities.d.a(Unknown Source:89)
01-15 12:02:26.426 10605 10638 W System.err: 	at com.mareksebera.simpledilbert.utilities.d.doInBackground(Unknown Source:2)
01-15 12:02:26.443  1622  2071 W NotificationService: Toast already killed. pkg=com.mareksebera.simpledilbert callback=android.app.ITransientNotification$Stub$Proxy@6b52219
01-15 12:02:26.446 10605 10605 I Toast   : Show toast from OpPackageName:com.mareksebera.simpledilbert, PackageName:com.mareksebera.simpledilbert
01-15 12:02:28.445  1622  2071 W NotificationService: Toast already killed. pkg=com.mareksebera.simpledilbert callback=android.app.ITransientNotification$Stub$Proxy@edd5424

**Comment by jhoc2000** [comment]
Hi Marek,

The app works intermittently and so far has loaded each time I start
it. It may take a while for it to fail for me to look at the logcat. If
it is fixed then I'm sure it is because of some way out app management
that Xiaomi has in its MIUI distribution. It's very annoying and I'm
very tempted to load a custom Android distribution such as LineageOS.

I'll contact you again if I get the error.

jhock.
